{% set name = "numpy_quaddtype" %}
{% set version = "0.0.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/SwayamInSync/numpy-user-dtypes/archive/refs/tags/quaddtype-v{{ version }}.tar.gz
  sha256: 57be7d7d848994f02809013920a8c712d495dd995a2d5a1be0fec76f51e2f45f

build:
  number: 2
  skip: True  # [py<310 or py>=313]
  script: |
    cd quaddtype
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pip
    - meson
    - meson-python
    - setuptools
    - sleef ==3.6.1
    - numpy >=2.0
  host:
    - python
    - pip
    - setuptools
    - meson
    - meson-python
    - sleef ==3.6.1
    - numpy >=2.0
  run:
    - python
    - sleef ==3.6.1
    - numpy >=2.0

test:
  imports:
    - numpy_quaddtype
  requires:
    - numpy >=2.0
    - pytest
  source_files:
    - quaddtype/tests
  commands:
    - pytest -s quaddtype/tests

about:
  home: https://github.com/numpy/numpy-user-dtypes
  summary: "Quad (128-bit) float dtype for numpy"
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SwayamInSync
