schema_version: 1

context:
  name: numpy_quaddtype
  pypi_name: numpy-quaddtype
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # For testing: use git repo instead of PyPI release
  - git: https://github.com/SwayamInSync/numpy-quaddtype.git
    branch: sleef-3.9
  # - url: https://pypi.org/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/numpy_quaddtype-${{ version }}.tar.gz
  #   sha256: <UPDATE_SHA256_WHEN_RELEASED>

build:
  number: 0
  script:
    - if: unix
      then:
        # taken from numpy feedstock to get cross-compilation working
        - if: build_platform != target_platform
          then:
            - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
            - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt
        - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
        - ${{ PYTHON }} -m pip install . -vv -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}
    - if: win
      then:
        - ${{ PYTHON }} -m mesonbuild.mesonmain setup %MESON_ARGS% builddir
        - set CFLAGS=%CFLAGS% /DDISABLE_QUADBLAS
        - set CXXFLAGS=%CXXFLAGS% /DDISABLE_QUADBLAS
        - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - pkg-config
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy >=2.4
        - sleef =3.9
  host:
    - python >=3.11
    - meson-python
    - numpy >=2.4
    - pip
    - setuptools
    - sleef =3.9
  run:
    - python >=3.11
    - numpy >=2.4

tests:
  - python:
      imports:
        - numpy_quaddtype
      pip_check: true
  - script:
      - pytest
    files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - mpmath

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A cross-platform Quad (128-bit) float Data-Type for NumPy.
  homepage: https://github.com/numpy/numpy-quaddtype
  repository: https://github.com/numpy/numpy-quaddtype

extra:
  recipe-maintainers:
    - SwayamInSync
