schema_version: 1

context:
  name: numpy_quaddtype
  pypi_name: numpy-quaddtype
  version: "0.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/numpy_quaddtype-${{ version }}.tar.gz
    sha256: 9eec9003aab53fb2ea12482dd5b4c0ad2ddf8bc2b9d2dfd05acc2ea46466d762
  # helpful for checking changes in the repo:
  # - git: https://github.com/numpy/numpy-user-dtypes.git
  #   branch: 0.2.x

build:
  number: 2
  script:
    # if repo is used as source:
    # - cd quaddtype
    - mkdir builddir
    - if: unix
      then:
        - ${{ PYTHON }} -m mesonbuild.mesonmain setup $MESON_ARGS builddir
    - if: win
      then:
        - ${{ PYTHON }} -m mesonbuild.mesonmain setup %MESON_ARGS% builddir
        - set CFLAGS=%CFLAGS% /DDISABLE_QUADBLAS
        - set CXXFLAGS=%CXXFLAGS% /DDISABLE_QUADBLAS
    - ${{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir
    - ${{ PYTHON }} -m pip install dist/numpy-quaddtype*.whl

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - numpy
        - sleef =3.8
  host:
    - python
    - python-build
    - meson-python
    - numpy
    - pip
    - setuptools
    - sleef =3.8
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - numpy_quaddtype
      pip_check: true
  - script:
      - pytest
    files:
      source:
        - tests/
        # if repo is used as source:
        # - quaddtype/tests/
    requirements:
      run:
        - pytest

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Quad (128-bit) float dtype for numpy
  homepage: https://github.com/numpy/numpy-user-dtypes
  repository: https://github.com/numpy/numpy-user-dtypes

extra:
  recipe-maintainers:
    - SwayamInSync
