schema_version: 1

context:
  name: numpy_quaddtype
  pypi_name: numpy-quaddtype
  version: "0.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ pypi_name[0] }}/${{ pypi_name }}/numpy_quaddtype-${{ version }}.tar.gz
    sha256: b97c59515b6cca34e3a8bb7cab36e5b2dbf1e6a552b1548f67d2bbe92605d60b

build:
  number: 1
  script:
    - if: unix
      then:
        # - ${{ PYTHON }} -m mesonbuild.mesonmain setup $MESON_ARGS builddir
        - if: build_platform != target_platform
          then:
            - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
            - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt
        - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
        - ${{ PYTHON }} -m pip install . -vv -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}
    - if: win
      then:
        - ${{ PYTHON }} -m mesonbuild.mesonmain setup %MESON_ARGS% builddir
        - set CFLAGS=%CFLAGS% /DDISABLE_QUADBLAS
        - set CXXFLAGS=%CXXFLAGS% /DDISABLE_QUADBLAS
        - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - pkg-config
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python
    - meson-python
    - numpy
    - pip
    - setuptools
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - numpy_quaddtype
      pip_check: true
  - script:
      - pytest
    files:
      source:
        - tests/
    requirements:
      run:
        - pytest

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Quad (128-bit) float dtype for numpy
  homepage: https://github.com/numpy/numpy-user-dtypes
  repository: https://github.com/numpy/numpy-user-dtypes

extra:
  recipe-maintainers:
    - SwayamInSync
