schema_version: 1

context:
  version: "1.0.0"

package:
  name: numpy_quaddtype
  version: ${{ version }}

source:
  # For testing: use git repo instead of PyPI release
  # Updated: tlfloat disabled in vendored SLEEF build
  - git: https://github.com/SwayamInSync/numpy-quaddtype.git
    branch: sleef-3.9
  # - url: https://pypi.org/packages/source/n/numpy-quaddtype/numpy_quaddtype-${{ version }}.tar.gz
  #   sha256: <UPDATE_SHA256_WHEN_RELEASED>

build:
  number: 0
  skip: match(python, "<3.11")
  script:
    - mkdir builddir
    - if: unix
      then: |
        ${{ PYTHON }} -m mesonbuild.mesonmain setup $MESON_ARGS builddir
        ${{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir
        ${{ PYTHON }} -m pip install dist/numpy_quaddtype*.whl
    - if: win
      then: |
        set "CFLAGS=%CFLAGS% /DDISABLE_QUADBLAS"
        set "CXXFLAGS=%CXXFLAGS% /DDISABLE_QUADBLAS"
        ${{ PYTHON }} -m mesonbuild.mesonmain setup %MESON_ARGS% builddir
        ${{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir
        :: from numpy feedstock:
        :: `pip install dist\numpy*.whl` does not work on windows,
        :: so use a loop; there's only one wheel in dist/ anyway
        for /f %%f in ('dir /b /S .\dist') do (
          pip install %%f
          if %ERRORLEVEL% neq 0 exit 1
        )

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
        - numpy >=2.4
        - sleef =3.9
  host:
    - python
    - python-build
    - meson-python
    - numpy >=2.4
    - pip
    - sleef =3.9
  run:
    - python
    - numpy >=2.4

tests:
  - python:
      imports:
        - numpy_quaddtype
      pip_check: true
  - script:
      - pytest
    files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - mpmath

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A cross-platform Quad (128-bit) float Data-Type for NumPy.
  homepage: https://github.com/numpy/numpy-quaddtype
  repository: https://github.com/numpy/numpy-quaddtype

extra:
  recipe-maintainers:
    - SwayamInSync
